services:
  #db
  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5433:5432" # Exposed only internally

  # back
  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
    env_file:
      - ./.env
    depends_on:
      - db

  # front
  # frontend:
  #   build: ./frontend # docker front
  #   container_name: coffee_frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - telegram      # run front after back


volumes:
  postgres-data: